# Generated by Django 5.0.4 on 2025-03-03 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiGroup",
            fields=[
                (
                    "group_name",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="api组名",
                    ),
                ),
                ("group_description", models.TextField(verbose_name="api组描述")),
            ],
            options={
                "verbose_name": "api组",
                "verbose_name_plural": "02-api组",
                "db_table": "api_group",
            },
        ),
        migrations.CreateModel(
            name="ApiInfo",
            fields=[
                (
                    "api_name",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="api名",
                    ),
                ),
                ("api_description", models.TextField(verbose_name="api描述")),
                ("api_url", models.CharField(max_length=255, verbose_name="api url")),
                ("api_docs", models.TextField(verbose_name="api文档")),
                (
                    "api_group",
                    models.ForeignKey(
                        db_column="api_group",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_info.apigroup",
                        verbose_name="班级",
                    ),
                ),
            ],
            options={
                "verbose_name": "api信息",
                "verbose_name_plural": "01-api信息",
                "db_table": "api_info",
            },
        ),
    ]
